[wokwi]
version = 1
firmware = '.pio/build/esp32doit-devkit-v1/firmware.elf'
gdbServerPort = 4000
rfc2217ServerPort = 4001

[[chip]]
name = 'mlx90614'
binary = 'chips/mlx90614.chip.wasm'

[[chip]]
name = 'max30102'
binary = 'chips/max30102.chip.wasm'